/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_eduardoguevara;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author edujg
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_personas = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_raza = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        js_ki = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        js_maxage = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        tf_planeta = new javax.swing.JTextField();
        bt_crear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cb_listahab = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tf_modraza = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        js_modki = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        js_modmaxage = new javax.swing.JSpinner();
        tf_modplaneta = new javax.swing.JTextField();
        bt_mod = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cb_elim = new javax.swing.JComboBox<>();
        bt_eliminarpp = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Raza:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 36, -1, -1));
        jPanel1.add(tf_raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 33, 110, 30));

        jLabel6.setText("Ki:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 81, -1, -1));

        js_ki.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 100));
        jPanel1.add(js_ki, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 78, 70, 30));

        jLabel7.setText("Cantidad Maxima de años:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 127, -1, -1));

        js_maxage.setModel(new javax.swing.SpinnerNumberModel());
        jPanel1.add(js_maxage, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 152, 70, 30));

        jLabel8.setText("Planeta:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 204, -1, -1));
        jPanel1.add(tf_planeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 196, 106, 31));

        bt_crear.setText("Crear");
        bt_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearMouseClicked(evt);
            }
        });
        jPanel1.add(bt_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jTabbedPane1.addTab("Crear SerVivo", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_listahab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_listahabItemStateChanged(evt);
            }
        });
        jPanel2.add(cb_listahab, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 11, 147, 28));

        jLabel1.setText("Raza:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 82, -1, -1));
        jPanel2.add(tf_modraza, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 75, 112, 29));

        jLabel2.setText("Ki:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        js_modki.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 100));
        jPanel2.add(js_modki, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 133, 81, 27));

        jLabel3.setText("Cantidad maxima de años:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 171, -1, -1));

        jLabel4.setText("Planeta:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 235, -1, -1));

        js_modmaxage.setModel(new javax.swing.SpinnerNumberModel());
        jPanel2.add(js_modmaxage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 80, 30));
        jPanel2.add(tf_modplaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 227, 114, 30));

        bt_mod.setText("Modificar");
        bt_mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modMouseClicked(evt);
            }
        });
        jPanel2.add(bt_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 231, -1, -1));

        jTabbedPane1.addTab("Modificar Personas", jPanel2);

        bt_eliminarpp.setText("Eliminar");
        bt_eliminarpp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarppMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(cb_elim, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(bt_eliminarpp)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cb_elim, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(bt_eliminarpp)
                .addGap(60, 60, 60))
        );

        jTabbedPane1.addTab("Eliminar Personas", jPanel3);

        javax.swing.GroupLayout jd_personasLayout = new javax.swing.GroupLayout(jd_personas.getContentPane());
        jd_personas.getContentPane().setLayout(jd_personasLayout);
        jd_personasLayout.setHorizontalGroup(
            jd_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jd_personasLayout.setVerticalGroup(
            jd_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Universo");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Crear Universo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setText("Cargar Universo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        ////////////
        ///////////////
        ///////////////
        ////////////

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        String universo = JOptionPane.showInputDialog("Ingrese el nombre del Universo");
        uni.add(new Universo(universo));
        this.dispose();
        actual = uni.get(uni.size() - 1);
        jd_personas.setModal(true);
        jd_personas.pack();
        jd_personas.setLocationRelativeTo(this);
        jd_personas.setVisible(true);
        try {
            JOptionPane.showMessageDialog(this, "Archivo creado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void bt_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearMouseClicked
        // TODO add your handling code here:
        SerVivo a = new SerVivo();
        a.setKi((int) js_ki.getValue());
        a.setMaxage((int) js_maxage.getValue());
        a.setPlaneta(tf_planeta.getText());
        a.setRaza(tf_raza.getText());
        actual.setPersona(a);
        js_ki.setValue(0);
        js_maxage.setValue(0);
        tf_planeta.setText("");
        tf_raza.setText("");
        System.out.println(a);
        try {
            actual.guardar();
            JOptionPane.showMessageDialog(this, "Guardado Correctamente");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
            ex.printStackTrace();
        }
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_listahab.getModel();
        DefaultComboBoxModel c = (DefaultComboBoxModel) cb_elim.getModel();
        //m.removeAllElements();
        //c.removeAllElements();
        m = new DefaultComboBoxModel();
        c = new DefaultComboBoxModel();
        for (int i = 0; i < actual.getHab().size(); i++) {
            m.addElement(actual.getHab().get(i));
            c.addElement(actual.getHab().get(i));
        }
        cb_listahab.setModel(m);
        cb_elim.setModel(c);
    }//GEN-LAST:event_bt_crearMouseClicked

    private void bt_modMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modMouseClicked
        // TODO add your handling code here:
        SerVivo c = (SerVivo) cb_listahab.getSelectedItem();
        for (int i = 0; i < actual.getHab().size(); i++) {
            if (c.equals(actual.getHab().get(i))) {
                JOptionPane.showMessageDialog(this, "Entro");
                actual.getHab().get(i).setKi((int) js_modki.getValue());
                actual.getHab().get(i).setMaxage((int) js_modmaxage.getValue());
                actual.getHab().get(i).setPlaneta(tf_modplaneta.getText());
                actual.getHab().get(i).setRaza(tf_modraza.getText());
            }
        }
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_listahab.getModel();
        DefaultComboBoxModel o = (DefaultComboBoxModel) cb_elim.getModel();
        //m.removeAllElements();
        //o.removeAllElements();
        m = new DefaultComboBoxModel();
        o = new DefaultComboBoxModel();
        for (int i = 0; i < actual.getHab().size(); i++) {
            m.addElement(actual.getHab().get(i));
            o.addElement(actual.getHab().get(i));
        }
        cb_listahab.setModel(m);
        cb_elim.setModel(o);
        try {
            actual.guardar();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bt_modMouseClicked

    private void cb_listahabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_listahabItemStateChanged
        // TODO add your handling code here:
        SerVivo c = (SerVivo) cb_listahab.getSelectedItem();
        tf_modraza.setText(c.getRaza());
        tf_modplaneta.setText(c.getPlaneta());
        js_modmaxage.setValue(c.getMaxage());
        js_modki.setValue(c.getKi());

    }//GEN-LAST:event_cb_listahabItemStateChanged

    private void bt_eliminarppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarppMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < actual.getHab().size(); i++) {
            if (cb_elim.getSelectedItem().equals(actual.getHab().get(i))) {
                System.out.println("entro");
                actual.getHab().remove(i);
            }
        }
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_listahab.getModel();
        DefaultComboBoxModel o = (DefaultComboBoxModel) cb_elim.getModel();
        m = new DefaultComboBoxModel();
        o = new DefaultComboBoxModel();
        for (int i = 0; i < actual.getHab().size(); i++) {
            m.addElement(actual.getHab().get(i));
            o.addElement(actual.getHab().get(i));
        }
        cb_listahab.setModel(m);
        cb_elim.setModel(o);
        try {
            actual.guardar();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_eliminarppMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        actual = new Universo();
        JFileChooser filechooser = new JFileChooser();
        int seleccion = filechooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(this, "Entrooooo");
            actual.setArchivo(filechooser.getSelectedFile());
            actual.cargar();
        }
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_listahab.getModel();
        DefaultComboBoxModel o = (DefaultComboBoxModel) cb_elim.getModel();
        m = new DefaultComboBoxModel();
        o = new DefaultComboBoxModel();
        for (int i = 0; i < actual.getHab().size(); i++) {
            m.addElement(actual.getHab().get(i));
            o.addElement(actual.getHab().get(i));
        }
        cb_listahab.setModel(m);
        cb_elim.setModel(o);
        this.dispose();
        jd_personas.setModal(true);
        jd_personas.pack();
        jd_personas.setLocationRelativeTo(this);
        jd_personas.setVisible(true);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    ArrayList<Universo> uni = new ArrayList();
    Universo actual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_crear;
    private javax.swing.JButton bt_eliminarpp;
    private javax.swing.JButton bt_mod;
    private javax.swing.JComboBox<String> cb_elim;
    private javax.swing.JComboBox<String> cb_listahab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_personas;
    private javax.swing.JSpinner js_ki;
    private javax.swing.JSpinner js_maxage;
    private javax.swing.JSpinner js_modki;
    private javax.swing.JSpinner js_modmaxage;
    private javax.swing.JTextField tf_modplaneta;
    private javax.swing.JTextField tf_modraza;
    private javax.swing.JTextField tf_planeta;
    private javax.swing.JTextField tf_raza;
    // End of variables declaration//GEN-END:variables
}
